# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6095c8cc0e62abcde59e6e08693236ef29e8787fe17a5292fe86798bf1714905fdde8fab6bdcda05db6c72453f67c3196a53aca5c061ecf11a2e56e1cbe1001

test:
  secret_key_base: 0be56e801ea2281c4f0d40cd5dc1908f10acb63e7a2d687bba11bef3c6a261b3bf207c6df23d01e421596e255b75ae047da500f923e1849d332f61098ab675ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
